-- =============================================
-- Inventory & Sales Management System
-- Functions
-- Author: Reuben Korsi Amuzu
-- =============================================

USE InventorySalesDB;
GO

-- Function 1: Check stock availability for a product
CREATE FUNCTION fn_GetStockQuantity(@ProductID INT)
RETURNS INT
AS
BEGIN
    DECLARE @Quantity INT;

    SELECT @Quantity = Quantity
    FROM Stock
    WHERE ProductID = @ProductID;

    RETURN ISNULL(@Quantity, 0);
END;
GO

-- Function 2: Get total amount spent by a customer
CREATE FUNCTION fn_GetCustomerTotal(@CustomerID INT)
RETURNS DECIMAL(10,2)
AS
BEGIN
    DECLARE @Total DECIMAL(10,2);

    SELECT @Total = SUM(si.Subtotal)
    FROM Sales s
    JOIN SaleItems si ON s.SaleID = si.SaleID
    WHERE s.CustomerID = @CustomerID;

    RETURN ISNULL(@Total, 0.00);
END;
GO

-- Function 3: Get total revenue generated by a category
CREATE FUNCTION fn_GetCategoryRevenue(@CategoryID INT)
RETURNS DECIMAL(10,2)
AS
BEGIN
    DECLARE @Revenue DECIMAL(10,2);

    SELECT @Revenue = SUM(si.Subtotal)
    FROM SaleItems si
    JOIN Products p ON si.ProductID  = p.ProductID
    WHERE p.CategoryID = @CategoryID;

    RETURN ISNULL(@Revenue, 0.00);
END;
GO